# -*- coding: utf-8 -*-
"""Covid_Analysis_using_pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xGOxxHvzWFJXF1LDz_Rqf7VkiZxOzZ_b
"""

# importing pandas library
import pandas as pd

# reading the csv file
complete_df = pd.read_csv("/content/complete.csv")

complete_df

# Head , Tail method used to give first ten and last ten values in the datasets
complete_df.head(5)

# This columns reads all column names
complete_df.columns

# iloc is used to locate the specified rows
complete_df.iloc[1]

# This iloc gives 2 refers to second row 1 refers to first value of the second row
complete_df.iloc[2,1]
# also we can give by using slicing method complete_df.iloc[1:10]

# This gives information about the specified columns
complete_df[['Name of State / UT','Total Confirmed cases','Death','Cured/Discharged/Migrated']]

complete_df[['Name of State / UT','New cases', 'New deaths', 'New recovered']]

# Groupby function is used for getting the total size , count
state_count_df = complete_df.groupby('Name of State / UT').size().reset_index(name='Total Count')

print(state_count_df)

# Groupby function is used to give total counts on each states with the specified columns
state_grouped_df1 = complete_df.groupby('Name of State / UT')['Total Confirmed cases', 'Death', 'Cured/Discharged/Migrated'].count().reset_index()

print(state_grouped_df1)

state_grouped_df2 = complete_df.groupby('Name of State / UT')['New cases', 'New deaths', 'New recovered'].count().reset_index()

state_grouped_df2

state_grouped_df=complete_df.groupby('Name of State / UT')['Total Confirmed cases', 'Death', 'Cured/Discharged/Migrated','New cases', 'New deaths', 'New recovered'].count().reset_index()

state_grouped_df

state_grouped_df

# Saving the modified csv file
state_grouped_df.to_csv("modified_complete_df.csv",index=False)

df=pd.read_csv("/content/modified_complete_df.csv")

df

nation_df=pd.read_csv("/content/nation_level_daily.csv")

nation_df.columns

nation_df

Total_nation_df=nation_df.groupby('Date')['Daily Confirmed', 'Total Confirmed', 'Daily Recovered',
       'Total Recovered', 'Daily Deceased', 'Total Deceased'].count().reset_index()

Total_nation_df

Total_nation_df.to_csv('modified_nation.csv')

district_df=pd.read_csv("/content/district_level_latest.csv")

district_df.columns

district_df.head(5)

count_district_df=district_df.groupby('State_Code').size().reset_index(name='Total_count')
count_district_df

groupby_state_df=district_df.groupby('State_Code')['District', 'Confirmed','Active', 'Recovered', 'Deceased', 'Migrated_Other', 'Delta_Confirmed','Delta_Active', 'Delta_Recovered', 'Delta_Deceased', 'Last_Updated'].count().reset_index()
groupby_state_df

groupby_state_df.to_csv("modified_district_level.csv")

df=pd.read_csv("/content/modified_district_level.csv")

df

df=pd.read_csv("/content/state_level_latest.csv")

df

df.columns

state_level_df=df.groupby(['State','Confirmed', 'Recovered', 'Deaths', 'Active',
       'Last_Updated_Time', 'Migrated_Other', 'State_code', 'Delta_Confirmed',
       'Delta_Recovered', 'Delta_Deaths']).size().reset_index()

state_level_df

state_level_df.to_csv("modified_state_level.csv")

df=pd.read_csv("/content/modified_state_level.csv")

df

# reading the patients data
df=pd.read_csv("/content/patients_data.csv")

df

df.columns

gender_df=df.groupby('Gender').size().reset_index(name='Total_count')

gender_df

State_code_df=df.groupby('State code').size().reset_index(name='Total_count')

State_code_df

